id: AB60DE613
title: Toh_174-The_Inquiry_of_Lokadhara-v2
type: translation
pechas:
- I4BC88634
- IE6C5C993
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-060-003
  eft-text-version: 1.1.9 2020
  title: Toh_174-The_Inquiry_of_Lokadhara-v2
alignment_to_base:
  I4BC88634/DCCC: '4726'
  IE6C5C993/FC8E: '4726'
